DecoRent/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Usuarios.urls')),
    path('Servicios/', include('Servicios.urls')),
    path('Solicitudes/', include('Solicitudes.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Servicios/urls.py
from django.urls import path
from . import views, views_stripe


urlpatterns = [
    path('', views.servicios_sin_login, name='servicios_sin_login'),
    path('publicar_servicio/', views.publicar_servicio, name='publicar_servicio'),
    path('publicacion_servicio/<int:id>/', views.publicacion_servicio, name='publicacion_servicio'), 
    path('publicacion_servicio/<int:id>/delete', views.eliminar_publicacion, name='eliminar_publicacion'), 
    path('editar_servicio/<int:servicio_id>/', views.editar_servicio, name='editar_servicio'),
    path('create_account/', views_stripe.create_account, name='create_account'),
    path('create_account_link/', views_stripe.create_account_link, name='create_account_link'),
    path('onboarding_complete/', views_stripe.stripe_onboarding_complete, name='stripe_onboarding_complete'),
    path('create_checkout_session/<int:solicitud_id>/', views_stripe.create_checkout_session, name='create_checkout_session'),
    path('payment_success/', views_stripe.payment_success, name='payment_success'),
    path('payment_cancel/', views_stripe.payment_cancel, name='payment_cancel'),
    path('stripe_dashboard/', views_stripe.stripe_dashboard_link, name='stripe_dashboard_link'),
    path('servicio/<int:solicitud_id>/agregar_reseña/', views.agregar_reseña, name='agregar_reseña'),
    path('perfil/', views.perfil, name='perfil'),
    ]

Servicios/models.py
from django.db import models
from Usuarios.models import Proveedor
from django.conf import settings


class Servicio(models.Model):
    """
    Clase implementada por Alan
    Modelo que representa un servicio ofrecido por un proveedor.

    Este modelo almacena la información relacionada con un servicio que un proveedor puede ofrecer
    a través de la plataforma. Incluye datos básicos como el nombre, la categoría, el precio mínimo,
    y detalles adicionales como la dirección y el promedio de calificación.

    Campos:
        proveedor (ForeignKey): Relación con el modelo `Proveedor`. Indica el proveedor que ofrece el servicio.
        nombre (CharField): Nombre del servicio (máximo 255 caracteres).
        categoria (CharField): Categoría a la que pertenece el servicio (máximo 255 caracteres).
        direccion (CharField): Dirección detallada donde se ofrece el servicio (máximo 500 caracteres).
        precio_minimo (DecimalField): Precio mínimo del servicio con dos decimales.
        informacion_detallada (TextField): Descripción detallada del servicio.
        promedio_calificacion (DecimalField): Calificación promedio del servicio. Valor máximo: 9.99 con dos decimales.
            Por defecto es 0.0 si no tiene calificaciones.

    Métodos:
        __str__():
            Devuelve una representación en cadena del servicio, incluyendo su nombre y el proveedor
            que lo ofrece.
    """
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255)
    categoria = models.CharField(max_length=255)
    direccion = models.CharField(max_length=500)
    precio_minimo = models.DecimalField(max_digits=10, decimal_places=2)
    informacion_detallada = models.TextField()
    promedio_calificacion = models.DecimalField(max_digits=3, decimal_places=2, default=0.0)
    
    def __str__(self):
        return self.nombre + ' - por ' + self.proveedor.nombre_empresa
    
class Imagenes_Servicios(models.Model):
    """
    Clase implementada por Alan
    Modelo que representa las imágenes asociadas a un servicio.

    Este modelo almacena las imágenes relacionadas con un servicio en la plataforma. Cada imagen
    está vinculada a un servicio específico y se guarda en una carpeta específica dentro del sistema
    de archivos del proyecto.

    Campos:
        servicio (ForeignKey): Relación con el modelo `Servicio`. Indica a qué servicio pertenece la imagen.
        imagen (ImageField): Archivo de imagen cargado, que se guarda en la ruta `media/servicios/`.
    """
    servicio = models.ForeignKey(Servicio, related_name='imagenes', on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='servicios/') #Las imagenes se guardan en la carpeta /media/servicios/ en de la raiz del proyecto


class Reseña(models.Model):
    """
    Modelo que representa una reseña de un servicio.

    Este modelo almacena las calificaciones y comentarios dejados por los usuarios para un servicio.
    Cada reseña incluye información sobre el servicio evaluado, el usuario que dejó la reseña, la
    calificación otorgada, un comentario opcional y la fecha en que se creó.

    Campos:
        servicio (ForeignKey): Relación con el modelo `Servicio`. Indica el servicio que fue evaluado.
        usuario (ForeignKey): Relación con el modelo de usuario (`AUTH_USER_MODEL`). Indica quién dejó la reseña.
        calificacion (PositiveSmallIntegerField): Calificación otorgada al servicio (valor entero positivo).
        comentario (TextField): Comentario opcional sobre el servicio. Puede ser nulo o estar en blanco.
        fecha (DateTimeField): Fecha y hora en que se creó la reseña. Se establece automáticamente.
    """
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE, related_name="reseñas")
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    calificacion = models.PositiveSmallIntegerField()
    comentario = models.TextField(blank=True, null=True)
    fecha = models.DateTimeField(auto_now_add=True)

Servicios/forms.py
from django import forms
from .models import Servicio, Imagenes_Servicios, Reseña
from django.forms.utils import flatatt

#Formulario para la publicacion de servicios
class PublicarServicioForm(forms.ModelForm):
    """
    Clase implementada por Alan
    Formulario para la publicación de servicios.

    Este formulario permite a los proveedores registrar nuevos servicios en la plataforma. Incluye campos
    específicos para los datos del servicio, como nombre, categoría, precio mínimo, y descripción, así
    como campos adicionales para capturar la dirección completa.

    Campos adicionales:
        - `calle` (CharField): Campo para ingresar la calle del servicio.
        - `numero_exterior` (CharField): Campo para ingresar el número exterior del servicio.
        - `numero_interior` (CharField): Campo opcional para el número interior del servicio.
        - `colonia` (CharField): Campo para ingresar la colonia del servicio.
        - `codigo_postal` (CharField): Campo para ingresar el código postal del servicio.

    Campos del modelo (`Servicio`):
        - `nombre` (CharField): Nombre del servicio.
        - `categoria` (CharField): Categoría del servicio. Opciones disponibles:
            - Entretenimiento
            - Equipamiento y mobiliario
            - Espacios para eventos
            - Catering
            - Fotografía
            - Decoración
            - Otro
        - `precio_minimo` (DecimalField): Precio mínimo del servicio.
        - `informacion_detallada` (TextField): Descripción detallada del servicio.

    Widgets personalizados:
        - `nombre`: Input de texto con la clase CSS `form-control`.
        - `categoria`: Selector de opciones (`form-select`) con categorías predefinidas.
        - `precio_minimo`: Input numérico con la clase CSS `form-control`.
        - `informacion_detallada`: Área de texto con la clase CSS `form-control`.

    Meta:
        - `model`: Relaciona el formulario con el modelo `Servicio`.
        - `fields`: Especifica los campos del modelo que estarán disponibles en el formulario.

    """
    calle = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    numero_exterior = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'class': 'form-control'}))
    numero_interior = forms.CharField(max_length=10, required=False, widget=forms.TextInput(attrs={'class': 'form-control'})) #Este campo es opcional
    colonia = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    codigo_postal = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'class': 'form-control'}))
    
    class Meta:
        model = Servicio #El modelo de este formulario es Servicio
        fields = ['nombre', 'categoria', 'precio_minimo','informacion_detallada']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'categoria': forms.Select(choices=[
                ('Entretenmiento', 'Entretenmiento'), 
                ('Equipamiento_Mobiliario', 'Equipamiento y mobiliario'), 
                ('Espacios_Eventos', 'Espacios para eventos'), 
                ('Catering', 'Catering'), 
                ('Fotografia', 'Fotografía'), 
                ('Decoracion', 'Decoración'),
                ('Otro', 'Otro'),], attrs={'class': 'form-select'}),
            'precio_minimo': forms.NumberInput(attrs={'class': 'form-control'}),
            'informacion_detallada': forms.Textarea(attrs={'class': 'form-control'}),
        }

#Clase personalizada para recibir multiples archivos
class MultipleFileField(forms.FileField):
    """
    Clase implementada por Alan
    Campo personalizado para manejar la carga de múltiples archivos.

    Esta clase extiende `forms.FileField` para permitir la selección y carga de múltiples
    archivos a través de un único campo en el formulario. Además, incluye la opción de
    establecer un número máximo de archivos permitidos.

    Atributos:
        max_num (int, opcional): Número máximo de archivos que se pueden cargar. Si no se
                                 proporciona, no hay límite.

    Métodos:
        __init__(*args, **kwargs):
            Inicializa el campo con atributos personalizados, como el soporte para múltiples
            archivos a través del atributo HTML `multiple`.

        clean(data, initial=None):
            Valida los datos proporcionados para este campo. En este caso, simplemente retorna
            los datos sin realizar validaciones adicionales.
    """
    def __init__(self, *args, **kwargs):
        self.max_num = kwargs.pop('max_num', None)
        super().__init__(*args, **kwargs)
        self.widget.attrs['multiple'] = True

    def clean(self, data, initial=None):
        """
        Valida los datos proporcionados para este campo.

        Args:
            data: Archivos cargados por el usuario.
            initial: Valor inicial del campo, si aplica.

        Returns:
            data: Retorna los datos sin aplicar validaciones adicionales.
        """
        return data
        
#Formulario para guardar multiples imagenes
class MultipleImagenesServiciosForm(forms.Form):
    imagen = MultipleFileField(max_num=5)
    
    class Meta:
        model = Imagenes_Servicios
        fields = ['imagen']
        
# codigo para editar publicacion 
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Servicio, Imagenes_Servicios
from .forms import PublicarServicioForm, MultipleImagenesServiciosForm

@login_required
def publicar_servicio(request):
    """
    Funcion implementada por Alan
    Vista para la publicación de un nuevo servicio.

    Esta función permite a los proveedores crear y publicar un nuevo servicio en la plataforma,
    incluyendo información detallada, dirección y las imágenes asociadas.

    Decoradores:
        @login_required: Requiere que el usuario esté autenticado y sea un proveedor.

    Args:
        request (HttpRequest): La solicitud HTTP enviada por el cliente. Puede ser de tipo POST para
                               guardar los datos del servicio, o GET para mostrar el formulario vacío.

    Funcionalidad:
        - Si la solicitud es de tipo POST:
            - Procesa el formulario de servicio (`PublicarServicioForm`) y el formulario de imágenes
              (`MultipleImagenesServiciosForm`).
            - Valida ambos formularios.
            - Guarda el servicio con los datos proporcionados y asigna el proveedor actual.
            - Guarda las imágenes cargadas asociándolas al servicio.
            - Redirige a la página de detalles del servicio después de guardar.
        - Si la solicitud no es de tipo POST (GET):
            - Muestra el formulario vacío para que el usuario pueda ingresar los datos del servicio.

    Returns:
        HttpResponse:
            - Si la solicitud es GET, renderiza la plantilla `publicar_servicio.html` con los formularios.
            - Si la solicitud es POST y los datos son válidos, redirige a la vista `detalle_servicio` con
              el ID del servicio recién creado.

    Contexto:
        - `servicio_form`: El formulario para ingresar los datos del servicio.
        - `imagenes_form`: El formulario para cargar imágenes relacionadas con el servicio.
    """
    if request.method == 'POST':
        # Procesa el formulario del servicio
        servicio_form = PublicarServicioForm(request.POST)
        imagenes_form = MultipleImagenesServiciosForm(request.FILES or None)
        
        if servicio_form.is_valid() and imagenes_form.is_valid():
            # Guardar el servicio
            servicio = servicio_form.save(commit=False)
            servicio.proveedor = request.user.proveedor  # Asigna el proveedor actual
            servicio.direccion = f"{servicio_form.cleaned_data['calle']} {servicio_form.cleaned_data['numero_exterior']} {servicio_form.cleaned_data.get('numero_interior', '')}, {servicio_form.cleaned_data['colonia']}, {servicio_form.cleaned_data['codigo_postal']}"
            servicio.save()

            # Guardar las imágenes
            for imagen in request.FILES.getlist('imagen'):
                Imagenes_Servicios.objects.create(servicio=servicio, imagen=imagen)

            return redirect('detalle_servicio', servicio_id=servicio.id)  # Redirige a la página de detalles del servicio después de guardar

    else:
        servicio_form = PublicarServicioForm()
        imagenes_form = MultipleImagenesServiciosForm()

    context = {
        'servicio_form': servicio_form,
        'imagenes_form': imagenes_form,
    }
    return render(request, 'publicar_servicio.html', context)

from django import forms
from .models import Reseña

class ReseñaForm(forms.ModelForm):
    """
    Formulario para agregar o editar una reseña.

    Este formulario permite a los usuarios ingresar una calificación y un comentario para un servicio.
    Está vinculado al modelo `Reseña` y personaliza los widgets para los campos.

    Meta:
        model (Reseña): Modelo relacionado al formulario.
        fields (list): Campos disponibles en el formulario, que incluyen:
            - `calificacion`: La calificación otorgada al servicio, seleccionada de un menú desplegable.
            - `comentario`: Comentario opcional sobre el servicio.
        widgets (dict): Configuración de widgets personalizados para los campos:
            - `calificacion`: Selector desplegable con opciones de 1 a 5 estrellas.
            - `comentario`: Área de texto con 3 filas predeterminadas.
    """
    class Meta:
        model = Reseña
        fields = ['calificacion', 'comentario']
        widgets = {
            'calificacion': forms.Select(choices=[(i, f"{i} estrellas") for i in range(1, 6)]),
            'comentario': forms.Textarea(attrs={'rows': 3}),
        }

Servicios/templates/payment_cancel.html
<!-- Hereda del archivo html base que incluye el navbar y footer -->
{% extends 'base.html' %}

<!-- Carga los archivos estaticos -->
{% load static %}

{% block title %} Pago exitoso {% endblock title %}

{% block css %}
<style>
    /* Hacer que el contenedor principal llene la altura de la pantalla */
    body, html {
        height: 100%;
        margin: 0;
        padding: 0;
        display: flex;
        flex-direction: column;
    }

    /* Contenedor que abarque el contenido */
    main {
        flex: 1;
        padding: 50px; /* Agregar margen interno para que el texto no esté pegado a los bordes */
        box-sizing: border-box;
    }

    /* Footer al final de la página */
    footer {
        background-color: #962b6b; /* Color de fondo del footer */
        color: #ffffff;
        padding: 10px;
        text-align: center;
    }
</style>
{% endblock css %}

{% block content %}

<main>
    <h1>Pago Cancelado</h1>
    <p>Has cancelado el proceso de pago. No se ha realizado ningún cargo y el servicio no ha sido reservado.</p>

    <h3>¿Tuviste problemas para completar el pago?</h3>
    <p>Algunos motivos comunes para la cancelación de pagos son:</p>
    <ul>
        <li>Problemas con el método de pago</li>
        <li>Interrupciones en la conexión</li>
        <li>Decisión de posponer la compra</li>
    </ul>

    <h3>¿Necesitas ayuda?</h3>
    <p>Si tienes algún problema o necesitas asistencia, contáctanos en:</p>
    <p>Email: soporte@decorent.com</p>
    <p>Teléfono: +52 123 456 7890</p>
</main>

{% endblock content %}

Servicios/templates/payment_success.html
<!-- Hereda del archivo html base que incluye el navbar y footer -->
{% extends 'base.html' %}

<!-- Carga los archivos estaticos -->
{% load static %}

{% block title %} Pago exitoso {% endblock title %}

{% block css %}
<style>
    /* Hacer que el contenedor principal llene la altura de la pantalla */
    body, html {
        height: 100%;
        margin: 0;
        padding: 0;
        display: flex;
        flex-direction: column;
    }

    /* Contenedor que abarque el contenido */
    main {
        flex: 1;
        padding: 50px 50px 0px 50px; /* Agregar margen interno para que el texto no esté pegado a los bordes */
        box-sizing: border-box;
    }

    /* Footer al final de la página */
    footer {
        background-color: #962b6b; /* Color de fondo del footer */
        color: #ffffff;
        padding: 10px;
        text-align: center;
    }
</style>
{% endblock css %}

{% block content %}

<main>
    <h1>¡Pago realizado con éxito!</h1>
    <p>Gracias por tu compra. Tu pago ha sido procesado correctamente.</p>
    <p>Enviaremos una notificación de confirmación de pago al proveedor del servicio.</p>
    <br>
    <h2>Detalles del servicio</h2>
    <p><strong>Nombre del servicio:</strong> {{ solicitud.servicio.nombre }}</p>
    <p><strong>Proveedor:</strong> {{ solicitud.proveedor.nombre_empresa }}</p>
    <p><strong>Contacto del proveedor:</strong> {{ solicitud.proveedor.user.email }}</p>
    <p><strong>Precio:</strong> ${{ solicitud.precio_con_iva|floatformat:2 }} MXN</p>
    <p><strong>Fecha del evento:</strong> {{ solicitud.fecha }}</p>
    <p><strong>Dirección del evento:</strong> {{ solicitud.direccion }}</p>
</main>

{% endblock content %}

Servicios/templates/publicar_servicio.html
<!-- Hereda del archivo html base que incluye el navbar y footer -->
{% extends 'base.html' %}

<!-- Carga los archivos estaticos -->
{% load static %}

{% block title %} Publicar Servicio {% endblock title %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/publicar_servicio.css' %}">
{% endblock css %}

{% block js %}
<!-- Script JavaScript para limpiar datos del formulario -->
<script>
/**
 * Limpia todos los campos del formulario de publicaci n de servicios.
 */
  function limpiarFormulario() {
    document.getElementById("miFormulario").reset(); // Resetea todos los campos del formulario
  }
</script>
{% endblock js %}

{% block content %}

<!-- Formulario para ingresar los datos de tu publicación -->
<form id="miFormulario" class="add-services" method="POST" enctype="multipart/form-data">
  <!-- Sección Información de la publicación -->
  <section class="containers-add-services sec-1">
    <h2>Información de la publicación</h2>
    <div class="buttons-containers">
      <button type="button" onclick="limpiarFormulario()" class="btn btn-primary add-btn">Limpiar</button>
      <button type="submit" class="btn btn-primary add-btn">Publicar</button>
    </div>
  </section>

  {% csrf_token %}

  <!-- Sección para ingresar tus datos -->
  <section class="containers-add-services sec-2">
    <div class="services-information item">
      <label for="id_nombre" class="text-label">Nombre del servicio:</label>
      <input type="text" name="nombre" class="config-input" maxlength="255" required="" id="id_nombre">
    </div>
    <div class="services-information item">
      <label for="id_calle" class="text-label">Calle:</label>
      <input type="text" name="calle" class="config-input" maxlength="255" required id="id_calle">
    </div>
    <div class="services-information item">
      <label for="id_numero_exterior" class="text-label">Numero exterior:</label>
      <input type="text" name="numero_exterior" class="config-input" maxlength="10" required id="id_numero_exterior">
    </div>
    <div class="services-information item">
      <label for="id_numero_interior" class="text-label">Numero interior:</label>
      <input type="text" name="numero_interior" class="config-input" maxlength="10" id="id_numero_interior">
    </div>
    <div class="services-information item">
      <label for="id_categoria" class="text-label sel-label">Categoria:</label>
      <select name="categoria" class="select-service" maxlength="255" id="id_categoria">
        <option value="Entretenimiento">Entretenmiento</option>
        <option value="Equipamiento_Mobiliario">Equipamiento y mobiliario</option>
        <option value="Espacios_Eventos">Espacios para eventos</option>
        <option value="Catering">Catering</option>
        <option value="Fotografia">Fotografía</option>
        <option value="Decoracion">Decoración</option>
        <option value="Otro">Otro</option>
      </select>
    </div>
    <div class="services-information item">
      <label for="id_colonia" class="text-label">Colonia:</label>
      <input type="text" name="colonia" class="config-input" maxlength="255" required id="id_colonia">
    </div>
    <div class="services-information item">
      <label for="id_codigo_postal" class="text-label">Codigo postal:</label>
      <input type="text" name="codigo_postal" class="config-input" maxlength="10" required id="id_codigo_postal">
    </div>
    <div class="services-information item">
      <label for="id_precio_minimo" class="text-label">Precio minimo:</label>
      <input type="number" name="precio_minimo" class="config-input" step="0.01" required id="id_precio_minimo">
    </div>
  </section>

  <!-- Sección para la información detallada de tu producto -->
  <section class="containers-add-services sec-3">
    <label for="id_informacion_detallada" class="lab-sec-3">Informacion detallada:</label>
    <textarea name="informacion_detallada" cols="40" rows="10" class="area-sec-3" required
      id="id_informacion_detallada"></textarea>
  </section>
  {{ error }}
  <!-- Sección para ingresar las fotos de tu producto -->
  <section class="containers-add-services sec-4">
    <label for="id_imagen" class="lab-sec-4">Carga de imágenes:</label>
    <div class="upload-container">
      <input type="file" name="imagen" multiple required id="id_imagen">
    </div>
  </section>
</form>

{% endblock content %}